### ISSUE TITLE
Training the agent does not work

### ISSUE THREAD

**Issue by raul1991** [rfeinman/TicTacToe-RL#1]
`python game.py q -t 5000`

Running the above didn't really do anything and just failed silently. Is there something missing here ?

**Comment by raul1991** [comment]
missing __main__  ?

**Comment by rfeinman** [comment]
Fixed - see https://github.com/rfeinman/tictactoe-reinforcement-learning/commit/71552fd01dce0eb7a5b97b2882de100692ecba30
The example commands from the readme were outdated.
